import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f5efe6',
  },
  page: {
    padding: 18,
    paddingBottom: 42,
  },
  hero: {
    backgroundColor: '#1f1a17',
    borderRadius: 28,
    padding: 24,
    marginBottom: 16,
  },
  kicker: {
    color: '#d8a16d',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  title: {
    color: '#fffaf4',
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '900',
    marginBottom: 10,
  },
  subtitle: {
    color: '#e6ddd4',
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 760,
  },
  meta: {
    color: '#c8b9ab',
    marginTop: 12,
    fontSize: 12,
  },
  heroButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  columns: {
    gap: 16,
  },
  columnsWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  column: {
    flex: 1,
    minWidth: 320,
  },
  leftColumn: {
    flex: 1.05,
  },
  rightColumn: {
    flex: 0.95,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    borderColor: '#eadfd3',
    borderRadius: 24,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#2b2018',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  cardHeaderCopy: {
    flex: 1,
  },
  cardTitle: {
    color: '#241b14',
    fontSize: 18,
    fontWeight: '900',
  },
  cardSubtitle: {
    color: '#6d625a',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: '#7b6d63',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#dccfc2',
    backgroundColor: '#fffdf9',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#1f1a17',
    fontSize: 15,
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#1f1a17',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondary: {
    backgroundColor: '#efe7de',
  },
  buttonDanger: {
    backgroundColor: '#8b3d2c',
  },
  buttonGhost: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#dbcab9',
  },
  buttonPressed: {
    opacity: 0.82,
  },
  buttonText: {
    color: '#fffaf4',
    fontWeight: '800',
    fontSize: 13,
  },
  buttonTextDark: {
    color: '#1f1a17',
  },
  buttonTextLight: {
    color: '#fffaf4',
  },
  pager: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
  pagerInfo: {
    flex: 1,
    alignItems: 'center',
  },
  pagerTitle: {
    color: '#1f1a17',
    fontSize: 13,
    fontWeight: '900',
  },
  pagerSub: {
    color: '#6d625a',
    fontSize: 12,
    marginTop: 2,
  },
  error: {
    color: '#8b3d2c',
    fontWeight: '800',
    marginBottom: 12,
  },
  list: {
    gap: 10,
  },
  listItem: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  questionItem: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  listItemActive: {
    backgroundColor: '#f8f0e7',
    borderColor: '#1f1a17',
  },
  questionItemActive: {
    backgroundColor: '#f8f0e7',
    borderColor: '#1f1a17',
  },
  listItemPressed: {
    opacity: 0.86,
  },
  listItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  listItemCopy: {
    flex: 1,
  },
  listItemTitle: {
    color: '#201913',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
  },
  listItemMeta: {
    color: '#75695f',
    fontSize: 12,
    marginTop: 4,
  },
  listItemDescription: {
    color: '#534a43',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#efe1d1',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#6d4b32',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailBox: {
    marginTop: 10,
    backgroundColor: '#faf4ec',
    borderWidth: 1,
    borderColor: '#ebded0',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  detailLabel: {
    color: '#7f7167',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 8,
  },
  detailValue: {
    color: '#1f1a17',
    fontSize: 13,
    lineHeight: 18,
  },
  liveNotice: {
    color: '#0f6a3c',
    fontWeight: '800',
    marginBottom: 12,
  },
  optionSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  answerChip: {
    backgroundColor: '#1f1a17',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  answerChipText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '800',
  },
  optionPick: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  optionPickActive: {
    backgroundColor: '#f7efe4',
    borderColor: '#1f1a17',
  },
  sessionActions: {
    marginTop: 14,
    gap: 10,
  },
  feedBox: {
    marginTop: 16,
    backgroundColor: '#f9f3ea',
    borderWidth: 1,
    borderColor: '#eadccb',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  feedItem: {
    color: '#4f463f',
    fontSize: 13,
    lineHeight: 18,
  },
  quizHeaderBox: {
    backgroundColor: '#f5ecdf',
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
  },
  quizHeaderTitle: {
    color: '#1f1a17',
    fontSize: 16,
    fontWeight: '900',
  },
  quizHeaderSub: {
    color: '#6f6258',
    fontSize: 12,
    marginTop: 4,
  },
  toggle: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#dbcab9',
    backgroundColor: '#f7f1e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
  },
  toggleActive: {
    borderColor: '#1f1a17',
    backgroundColor: '#1f1a17',
  },
  toggleText: {
    color: '#1f1a17',
    fontWeight: '800',
    fontSize: 12,
  },
  toggleTextActive: {
    color: '#fffaf4',
  },
  optionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  optionsTitle: {
    color: '#1f1a17',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  optionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 10,
    alignItems: 'flex-end',
  },
  optionField: {
    flex: 1,
    minWidth: 120,
  },
  optionLabelRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  optionLabelChip: {
    borderWidth: 1,
    borderColor: '#dbcab9',
    backgroundColor: '#f7f1e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  optionLabelChipActive: {
    borderColor: '#1f1a17',
    backgroundColor: '#1f1a17',
  },
  optionLabelText: {
    color: '#1f1a17',
    fontWeight: '800',
    fontSize: 12,
  },
  optionLabelTextActive: {
    color: '#fffaf4',
  },
  optionRemove: {
    alignSelf: 'flex-end',
  },
  optionChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  optionWord: {
    color: '#1f1a17',
    fontSize: 13,
    fontWeight: '700',
  },
  emptyState: {
    backgroundColor: '#f8f3ea',
    borderWidth: 1,
    borderColor: '#eadccb',
    borderRadius: 18,
    padding: 20,
  },
  emptyStateTitle: {
    color: '#1f1a17',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 6,
  },
  emptyStateBody: {
    color: '#665c54',
    lineHeight: 20,
  },
  note: {
    color: '#4f463f',
    lineHeight: 20,
    marginBottom: 8,
  },
  footer: {
    marginTop: 8,
    paddingVertical: 8,
  },
  footerText: {
    color: '#71655c',
    fontSize: 12,
  },
});
